---
title: "Dominica: Sperm Whale Sightings"
output: html_document
date: "2023-05-01"
---

```{r setup, include=FALSE}
# Load common helper script
source(here::here("common.R"))

# Define nautical miles in m
nm <- 1852

# Load reserve boundaries
load(here::here("results", "reserve_boundaries.Rdata"))

# Load sperm whale sightings
whales <- read_csv(file.path(prj_cachalote_dir, "data", "raw", "sightings.csv")) %>%
  rowwise() %>%
  mutate(datetime_rev = as.POSIXlt(datetime, format = "%m/%d/%Y %H:%M"),
         year = year(datetime_rev)) %>%
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326) %>%
  rename(obs = 1) %>%
  sf::st_transform(crs = st_crs(prj_moll)) # convert points to Mollewide
```

# Introduction

This script loads the database of sperm whale sightings around Dominica from 2005 - 2018 shared with us by Shane Gero and assessed the proportion of total sightings each year that fall within the boundaries of the proposed reserve(s). 

```{r}
# Add scenario name
reserve_boundaries_sf <- reserve_boundaries_sf %>%
  mutate(scenario_name = paste0(W_lon, "°W"))

# Plot 
whales_and_reserves_plot <- ggplot()+
  geom_sf(data = dominica_eez_sf_moll, aes(group = mrgid), color = "black", fill = "grey", size = 0.2)+
  geom_sf(data = whales, size = 0.02, fill = "black")+
  geom_sf(data = reserve_boundaries_sf, aes(fill = scenario), alpha = 0.3)+
  coord_sf(xlim = plot_bbox$xlim, ylim = plot_bbox$ylim)+
  facet_wrap(~scenario_name, nrow = 1)+
  theme_basic()+
  guides(fill = "none")+
  labs(title = "Potential reserve boundaries overlaid on sperm whale sightings (2005 - 2018)")

ggsave(file.path(prj_cachalote_dir, "figures", "potential_reserve_boundaries_and_whale_sightings_map.png"), whales_and_reserves_plot)

whales_and_reserves_plot
```

```{r}
# Plot again by year
whales_and_reserves_plot_by_year <- ggplot()+
  geom_sf(data = dominica_eez_sf_moll, aes(group = mrgid), color = "black", fill = "grey", size = 0.2)+
  geom_sf(data = whales %>% dplyr::filter(year >= 2014), size = 0.02, fill = "black")+
  geom_sf(data = reserve_boundaries_sf, aes(fill = scenario), alpha = 0.3)+
  coord_sf(xlim = plot_bbox$xlim, ylim = plot_bbox$ylim)+
  facet_grid(year~scenario_name)+
  theme_basic()+
  guides(fill = "none")+
  labs(title = "Potential reserve boundaries overlaid on sperm whale sightings (2014 - 2018)")

ggsave(file.path(prj_cachalote_dir, "figures", "potential_reserve_boundries_and_whale_sightings_by_year_map.png"), whales_and_reserves_plot_by_year)

whales_and_reserves_plot_by_year
```

# Summarize by Reserve Design and Year

```{r}
# Get totals by year
totals_by_year <- whales %>%
  st_drop_geometry() %>%
  group_by(year) %>%
  summarize(n_sightings_total = n_distinct(obs),
            n_adults_total = sum(adults, na.rm = T),
            n_calves_total = sum(calves, na.rm = T),
            n_whales_total = sum(total, na.rm = T))

# Determine which reserve(s) each observation would fall within
where_be_whales <- st_join(whales, reserve_boundaries_sf) %>%
  dplyr::filter(!is.na(scenario))
  
# Summarize by year and reserve design
summary_by_year <- where_be_whales %>%
  st_drop_geometry() %>%
  group_by(year, scenario, scenario_name, area_km2) %>%
  summarize(n_sightings = n_distinct(obs),
            n_adults = sum(adults, na.rm = T),
            n_calves = sum(calves, na.rm = T),
            n_whales = sum(total, na.rm = T)) %>%
  ungroup() %>%
  left_join(totals_by_year, by = "year") %>%
  mutate(prop_sightings = n_sightings/n_sightings_total,
         prop_adults = n_adults/n_adults_total,
         prop_calves = n_calves/n_calves_total,
         prop_whales = n_whales/n_whales_total) %>%
  dplyr::select(year, scenario, scenario_name, area_km2, contains("prop")) %>%
  gather("obs_type", "value", contains("prop")) %>%
  mutate(obs_type = str_replace(obs_type, "prop_", ""))
```

## Visualize

```{r}
# Plot reserve area versus sightings
tradeoff_plot <- summary_by_year %>%
  ggplot()+
  aes(x = area_km2, y = value, color = obs_type)+
  geom_point(aes(shape = scenario_name), size = 2)+
  geom_line()+
  theme_basic()+
  facet_wrap(~ year)+
  labs(x = "Reserve area (km2)", y = "Prop. of observations", title = "Proportion of sperm whale sightings within potential reserves by area (2005 - 2018)")+
  guides(color = guide_legend(title = "Observation type"),
         shape = guide_legend(title = "Longitude of W reserve boundary", reverse = T))
  
ggsave(file.path(prj_cachalote_dir, "figures", "prop_whale_sightings_by_reserve_and_year.png"), tradeoff_plot, width = 10.5, height = 7.5)

tradeoff_plot
```

```{r}
# Plot reserve design versus proportion of sightings
tradeoff_plot_bar <- summary_by_year %>%
  ggplot()+
  aes(x = year, y = value, fill = scenario)+
  geom_bar(position = "dodge", stat = "identity", alpha = 0.4)+
  scale_y_continuous(limits = c(0,1))+
  scale_fill_gradient(breaks = c(1,2,3), limits = c(1,3))+
  theme_basic()+
  facet_wrap(~ obs_type, ncol = 1)+
  labs(x = "Year", y = "Prop. of observations", title = "Proportion of sperm whale sightings within potential reserves (2005 - 2018)")+
  guides(fill = guide_colorbar(title = "Scenario"))

ggsave(file.path(prj_cachalote_dir, "figures", "prop_whale_sightings_by_reserve_and_year_bar.png"), tradeoff_plot_bar, width = 7.5, height = 10)

tradeoff_plot_bar
```


