---
title: "Dominica: Process GFW Voyage Data"
output: html_document
date: "2023-05-01"
---

```{r setup, include=FALSE}
# Packages
library(DBI)
library(bigrquery)
library(networkD3) # Make flow diagram
library(webshot) # Save static version of flow diagram

# Load common helper script
source(here::here("common.R"))

# Load reserve boundaries
load(here::here("results", "reserve_boundaries.Rdata"))

# Setup BQ connections
bq_auth_id <- "kmillage@ucsb.edu"

# Bigquery project for billing
bq_project <-  "emlab-gcp"

# Solution to bigrquery error (August 5, 2020) - see https://github.com/r-dbi/bigrquery/issues/395 for details
options(scipen = 20)
```

# Introduction

This script queries the GFW port and voyages tables to find trips that start/end in Dominica. 

# Identify ports/anchorages in Dominica

```{r}
sql_port_index <- "#StandardSQL

  # Select Anchorage information for all ports in Dominica
  
  SELECT 
    s2id AS anchorage_id,
    label AS anchorage_name,
    sublabel AS anchorage_sublabel,
    lat,
    lon,
    total_visits,
    top_destination,
    iso3,
    distance_from_shore_m,
    dock
  FROM 
    `world-fishing-827.anchorages.named_anchorages_v20230302`
  WHERE 
    iso3 = 'DMA'
  ORDER BY anchorage_name"
```

```{r query-port-index, eval=F}
# Table to save output
port_index_table <- bq_table(project = bq_project,
                             table = "port_index",
                             dataset = "dominica")

if(bq_table_exists(port_index_table)){
  bq_table_delete(port_index_table)
}else{
  bq_table_create(port_index_table)
}

# Run query - We have 25 named anchorages 
dom_ports <- bq_project_query(bq_project, 
                              query = sql_port_index,
                              destination_table = port_index_table,
                              use_legacy_sql = FALSE,
                              allowLargeResults = TRUE) %>%
  bq_table_download()

# Save locally too
write_csv(dom_ports, file.path(prj_cachalote_dir, "data", "processed", "dominica_anchorages_gfw.csv"))
```

```{r}
# Make ports spatial
dom_ports_sf <- dom_ports %>%
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = F) %>%
  sf::st_transform(crs = st_crs(prj_moll)) # convert points to Mollewide

# Plot 
anchorages_plot <- ggplot()+
  geom_sf(data = dominica_eez_sf_moll, aes(group = mrgid), color = "black", fill = "grey", size = 0.2)+
  geom_sf(data = reserve_boundaries_sf, aes(fill = scenario), alpha = 0.4)+
  geom_sf(data = dom_ports_sf, aes(size = total_visits, color = anchorage_name), alpha = 0.3)+
  coord_sf(xlim = plot_bbox$xlim, ylim = plot_bbox$ylim)+
  theme_basic()+
  guides(color = guide_legend(title = "Name", nrow = 3),
         fill = "none",
         size = guide_legend(title = "Total visits"))+
  labs(title = "Named anchorages in Dominica identified by GFW")

ggsave(file.path(prj_cachalote_dir, "figures", "dominica_anchorages.png"), anchorages_plot, height = 8, width = 8)

anchorages_plot
```

```{r}
# Now calculate centroid by group
dom_ports_centroid_sf <- dom_ports_sf %>%
  mutate(port_group = case_when(anchorage_name == "PORTSMOUTH" ~ "Portsmouth",
                                anchorage_name %in% c("ROSEAU", "POINTE MICHEL") ~ "Roseau/Pointe Michel",
                                anchorage_name %in% c("DMA-4", "SAINT JOSEPH") ~ "Saint Joseph/Salisbury")) %>%
  group_by(port_group) %>%
  mutate(lat_cen = mean(lat),
         lon_cen = mean(lon)) %>%
  ungroup() %>%
  st_drop_geometry() %>%
  st_as_sf(coords = c("lon_cen", "lat_cen"),
           crs = 4326,
           remove = F) %>%
  sf::st_transform(crs = st_crs(prj_moll)) # convert points to Mollewide

# Plot 
anchorage_centroid_plot <- ggplot()+
  geom_sf(data = dominica_eez_sf_moll, aes(group = mrgid), color = "black", fill = "grey", size = 0.2)+
  geom_sf(data = reserve_boundaries_sf, aes(fill = scenario), alpha = 0.3)+
  geom_sf(data = dom_ports_centroid_sf, aes(color = port_group))+
  coord_sf(xlim = plot_bbox$xlim, ylim = plot_bbox$ylim)+
  theme_basic()+
  guides(color = guide_legend(title = "Anchorage group", nrow = 3),
         fill = "none")+
  labs(title = "Anchorage groups in Dominica identified by GFW")

ggsave(file.path(prj_cachalote_dir, "figures", "dominica_anchorage_groups.png"), anchorage_centroid_plot, height = 8, width = 8)

anchorages_plot
```

```{r}
# Save anchorage information
save(dom_ports_centroid_sf, 
     file = file.path(prj_cachalote_dir, "data", "processed", "dominica_anchorage_centroids_gfw.Rdata"))
```

# Identify voyages starting or ending at anchorages in Dominica

```{r}
sql_dom_voyages <- "#StandardSQL

WITH 

  #########################
  # Anchorage info we want to add to this table

  anchorages AS (
      SELECT
        s2id AS anchorage_id,
        label AS anchorage_name,
        sublabel AS anchorage_sublabel,
        iso3
      FROM 
        `world-fishing-827.anchorages.named_anchorages_v20230302`
  ),

  #########################
  # List of known bad mmsi numbers

  bad_mmsi AS (
      SELECT
        ssvid
      FROM
        `world-fishing-827.gfw_research.bad_mmsi`
      CROSS JOIN
      UNNEST(ssvid) AS ssvid
  ),
  
  #########################
  # All voyages by vessels with a port visit confidence 4 - if we want to lower this confidence, we'll need to pull from a different table
  
  good_voyages AS(
      SELECT 
        *,
        EXTRACT(YEAR FROM trip_start) AS start_year,
        EXTRACT(YEAR FROM trip_end) AS end_year
      FROM  
        `world-fishing-827.pipe_production_v20201001.voyages`
      WHERE
        EXTRACT(YEAR FROM trip_start) > 2016 
        AND EXTRACT(YEAR FROM trip_end) < 2023
        AND CAST(ssvid AS int64) NOT IN (
                  SELECT
                    ssvid
                  FROM
                    bad_mmsi)
          AND trip_start_anchorage_id IN (
                  SELECT
                    anchorage_id
                  FROM
                    `emlab-gcp.dominica.port_index`)         
      UNION ALL
      SELECT 
        *,
        EXTRACT(YEAR FROM trip_start) AS start_year,
        EXTRACT(YEAR FROM trip_end) AS end_year
      FROM  
        `world-fishing-827.pipe_production_v20201001.voyages`
      WHERE
        EXTRACT(YEAR FROM trip_start) > 2016 
        AND EXTRACT(YEAR FROM trip_end) < 2023
        AND CAST(ssvid AS int64) NOT IN (
                  SELECT
                    ssvid
                  FROM
                    bad_mmsi)
          AND trip_end_anchorage_id IN (
                  SELECT
                    anchorage_id
                  FROM
                    `emlab-gcp.dominica.port_index`)
      )


  SELECT 
    ssvid,
    trip_id,
    trip_start AS start_timestamp,
    start_year,
    trip_start_visit_id AS start_visit_id,
    g.trip_start_anchorage_id as start_anchorage_id,
    c.anchorage_name AS start_anchorage_name,
    c.anchorage_sublabel AS start_anchorage_sublabel,
    c.iso3 AS start_iso3,
    IF(c.iso3 = 'DMA', TRUE, FALSE) AS start_is_DMA,
    trip_end AS end_timestamp,
    end_year,
    g.trip_end_anchorage_id as end_anchorage_id,
    d.anchorage_name AS end_anchorage_name,
    d.anchorage_sublabel AS end_anchorage_sublabel,
    d.iso3 AS end_iso3,
    IF(d.iso3 = 'DMA', TRUE, FALSE) AS end_is_DMA,
    DATETIME_DIFF(trip_end, trip_start, MINUTE)/60 AS voyage_duration_h
  FROM good_voyages as g
  INNER JOIN anchorages as c
  ON g.trip_start_anchorage_id = c.anchorage_id
  INNER JOIN anchorages as d
  ON g.trip_end_anchorage_id = d.anchorage_id"
```

```{r query-voyages, eval=F}
# Table to save output
voyage_table <- bq_table(project = bq_project,
                         table = "dominica_voyages_2017_2022",
                         dataset = "dominica")

if(bq_table_exists(voyage_table)){
  bq_table_delete(voyage_table)
}else{
  bq_table_create(voyage_table)
}

# Run query
dom_voyages <- bq_project_query(bq_project, 
                                query = sql_dom_voyages,
                                destination_table = voyage_table,
                                use_legacy_sql = FALSE,
                                allowLargeResults = TRUE) %>%
  bq_table_download()

# Save locally too
write_csv(dom_voyages, file.path(prj_cachalote_dir, "data", "processed", "dominica_voyages_gfw_2017_2022.csv"))
```

# Frequency of voyages by start/end country

```{r}
# Summarize by start/end - country level only
freq_voyages_by_iso3 <- dom_voyages %>%
  group_by(start_year, start_iso3, end_iso3) %>%
  summarize(n_voyages = n_distinct(trip_id),
            avg_duration_h = mean(voyage_duration_h))
```

```{r}
# Plot flow diagram of voyages to Dominica
links_in <- freq_voyages_by_iso3 %>%
  ungroup() %>%
  dplyr::filter(start_year == 2022 & start_iso3 != "DMA" & end_iso3 == "DMA") %>%
  dplyr::select(source = start_iso3, target = end_iso3, value = n_voyages)
links_in$source <- paste(links_in$source, " ", sep="")

# Plot flow diagram of total landings made in each country that go toward each destination
links_out <- freq_voyages_by_iso3 %>%
  ungroup() %>%
  dplyr::filter(start_year == 2022 & start_iso3 == "DMA") %>%
  dplyr::select(source = start_iso3, target = end_iso3, value = n_voyages)

# Join to previous df
links_all <- links_in %>%
  bind_rows(links_out)

nodes <- tibble(name=c(as.character(links_all$source), as.character(links_all$target)) %>% unique()) %>%
  mutate(region = countrycode(str_replace(name, " ", ""), "iso3c", "region"),
         group = case_when(region == "Latin America & Caribbean" ~ "group_1",
                           region == "Sub-Saharan Africa" ~ "group_2",
                           region == "Europe & Central Asia" ~ "group_3",
                           region == "North America" ~ "group_4",
                           T ~ "group_5"),
         group = as.factor(group)) %>%
  as.data.frame()

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links_all$IDsource=match(links_all$source, nodes$name)-1 
links_all$IDtarget=match(links_all$target, nodes$name)-1

# Color scale
# rev(RColorBrewer::brewer.pal(3, "Set2"))
my_color <- 'd3.scaleOrdinal() .domain(["group_1", "group_2", "group_3", "group_4", "group_5"]) .range(["#8DA0CB", "#FC8D62", "#66C2A5", "#6ca992", "grey"])'

# Make plot
sn <- sankeyNetwork(Links = links_all, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name",
              sinksRight=F, nodeWidth=40, fontSize=13, nodePadding=20,
              iterations = 100,
              units = "Voyages",
              NodeGroup ="group",
              colourScale = my_color)

# Save
saveNetwork(sn, file.path(prj_cachalote_dir, "figures", "voyages_in_and_out_of_dominica_by_iso3.html"))

# # And convert to a static PNG version
# webshot(here("results", "voyages_in_and_out_of_dominica_by_iso3.html"),
#         here("results", "voyages_in_and_out_of_dominica_by_iso3.png"), vwidth = 2500, vheight = 1500)

sn
```

```{r}
# Summarize by start/end - by port are within Dominica
freq_voyages_by_iso3_and_port <- dom_voyages %>%
  mutate(start_anchor_group = case_when(start_anchorage_name %in% c("POINTE MICHEL", "ROSEAU") ~ "Roseau/Pointe Michel",
                                        start_anchorage_name == "PORTSMOUTH" ~ "Portsmouth",
                                        start_anchorage_name %in% c("DMA-4", "SAINT JOSEPH") ~ "Saint Joseph/Salisbury"),
         end_anchor_group = case_when(end_anchorage_name %in% c("POINTE MICHEL", "ROSEAU") ~ "Roseau/Pointe Michel",
                                      end_anchorage_name == "PORTSMOUTH" ~ "Portsmouth",
                                      end_anchorage_name %in% c("DMA-4", "SAINT JOSEPH") ~ "Saint Joseph/Salisbury")) %>%
  mutate(start = ifelse(start_iso3 == "DMA", start_anchor_group, start_iso3),
         end = ifelse(end_iso3 == "DMA", end_anchor_group, end_iso3)) %>%
  group_by(start_year, start, end) %>%
  summarize(n_voyages = n_distinct(trip_id),
            avg_duration_h = mean(voyage_duration_h))

# Remove those with the same start/end destination
freq_voyages_by_iso3_and_port <- freq_voyages_by_iso3_and_port %>%
  dplyr::filter(start != end)
```

```{r}
# Plot flow diagram of voyages to Dominica
links_in_p <- freq_voyages_by_iso3_and_port %>%
  ungroup() %>%
  dplyr::filter(start_year == 2022 & end %in% c("Roseau/Pointe Michel", "Saint Joseph/Salisbury", "Portsmouth")) %>%
  dplyr::select(source = start, target = end, value = n_voyages)
links_in_p$source <- paste(links_in_p$source, " ", sep="")

# Plot flow diagram of total landings made in each country that go toward each destination
links_out_p <- freq_voyages_by_iso3_and_port %>%
  ungroup() %>%
  dplyr::filter(start_year == 2022 & start %in% c("Roseau/Pointe Michel", "Saint Joseph/Salisbury", "Portsmouth")) %>%
  dplyr::select(source = start, target = end, value = n_voyages)
links_out_p$target <- paste(links_out_p$target, "  ", sep="")

# Join to previous df
links_all_p <- links_in_p %>%
  bind_rows(links_out_p)

nodes_p <- tibble(name=c(as.character(links_all_p$source), as.character(links_all_p$target)) %>% unique()) %>%
  mutate(region = countrycode(str_replace_all(name, " ", ""), "iso3c", "region"),
         group = case_when(region == "Latin America & Caribbean" ~ "group_1",
                           region == "Sub-Saharan Africa" ~ "group_2",
                           region == "Europe & Central Asia" ~ "group_3",
                           region == "North America" ~ "group_4",
                           T ~ "group_5"),
         group = as.factor(group)) %>%
  as.data.frame()

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links_all_p$IDsource=match(links_all_p$source, nodes_p$name)-1 
links_all_p$IDtarget=match(links_all_p$target, nodes_p$name)-1

# Color scale
# rev(RColorBrewer::brewer.pal(3, "Set2"))
my_color <- 'd3.scaleOrdinal() .domain(["group_1", "group_2", "group_3", "group_4", "group_5"]) .range(["#8DA0CB", "#FC8D62", "#66C2A5", "#6ca992", "grey"])'

# Make plot
sn_p <- sankeyNetwork(Links = links_all_p, Nodes = nodes_p,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name",
              sinksRight=F, nodeWidth=40, fontSize=13, nodePadding=20,
              iterations = 100,
              units = "Voyages",
              NodeGroup ="group",
              colourScale = my_color)

# Save
saveNetwork(sn_p, file.path(prj_cachalote_dir, "figures", "voyages_in_and_out_of_dominica_by_iso3_and_port.html"))

# # And convert to a static PNG version
# webshot(here("results", "voyages_in_and_out_of_dominica_by_iso3.html"),
#         here("results", "voyages_in_and_out_of_dominica_by_iso3.png"), vwidth = 2500, vheight = 1500)

sn_p
```


